package org.generator.pojo;

public class Employee {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employee.id
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employee.last_name
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    private String lastName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employee.gender
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    private String gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employee.email
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_employee.dept_id
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    private Integer deptId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.id
     *
     * @return the value of tb_employee.id
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.id
     *
     * @param id the value for tb_employee.id
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.last_name
     *
     * @return the value of tb_employee.last_name
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.last_name
     *
     * @param lastName the value for tb_employee.last_name
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.gender
     *
     * @return the value of tb_employee.gender
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    public String getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.gender
     *
     * @param gender the value for tb_employee.gender
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    public void setGender(String gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.email
     *
     * @return the value of tb_employee.email
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.email
     *
     * @param email the value for tb_employee.email
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_employee.dept_id
     *
     * @return the value of tb_employee.dept_id
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_employee.dept_id
     *
     * @param deptId the value for tb_employee.dept_id
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }
}