package org.generator.dao;

import java.util.List;
import org.generator.pojo.Dem;

public interface DemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_department
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_department
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    int insert(Dem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_department
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    Dem selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_department
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    List<Dem> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_department
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    int updateByPrimaryKey(Dem record);
}