package org.generator.dao;

import java.util.List;
import org.generator.pojo.Employee;

public interface EmployeeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_employee
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_employee
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    int insert(Employee record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_employee
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    Employee selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_employee
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    List<Employee> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_employee
     *
     * @mbg.generated Tue Dec 08 15:48:50 CST 2020
     */
    int updateByPrimaryKey(Employee record);
}